### ISSUE TITLE
how to add the package in Sencha Architect?

### ISSUE THREAD

**Issue by gtoto007** [JarvusInnovations/jarvus-touch-fieldscroller#2]
Can you help me better understand how to add this package in my project of Sencha Architect? I have a folder called "packages" and I created a sub folder with the name "jarvus-touch fieldscroller" and I put in the files of your project. Then I added in array "requires" the  string 'jarvus-touch fieldscroller' in file app.json but I have error
GET http: // localhost: 1841 / jarvus-touch fieldscroller.js? _dc = 1416133152690 sencha-touch.js: 8304
Uncaught Error: [Ext.Loader] Failed loading 'jarvus-touch fieldscroller.js', please verify That the file exists

I tried to read the documentation on the official site but could not find what I needed.

**Comment by themightychris** [comment]
@gtoto007 I'm not completely familiar with how things work under Architect, but after following that process with a Sencha CMD-generated project you would get an error like that until you ran `sencha app refresh`. That command scans all your app and package source files and updates bootstrap.js to map all the class names to where they can be found and autoload all overrides.

**Comment by gtoto007** [comment]
HI @themightychris, thank you for your response.

Now I am trying to create an app from scratch using Sencha Cmd but still not be able to import the package.

These are the commands that launch:
1) sencha -sdk touch generate app MyApp myapp
2) cd myapp
3) cd packages
4) git clone https://github.com/JarvusInnovations/jarvus-touch-fieldscroller.git 
This is the current situation:
![schermata 2014-11-16 alle 16 44 59](https://cloud.githubusercontent.com/assets/6715157/5062003/f1036f98-6daf-11e4-832f-f0b87a2c957f.png)

5)now, i launch "sencha app refresh" and do not notice changes in bootstrap.js
6) i edit file "app.js" and add jarvus-touch-fieldscroller in requires
![schermata 2014-11-16 alle 16 48 56](https://cloud.githubusercontent.com/assets/6715157/5062020/7eebdee4-6db0-11e4-80cc-56ef3b303082.png)
7) i launch "sencha app refresh" but i have error
![schermata 2014-11-16 alle 16 49 48](https://cloud.githubusercontent.com/assets/6715157/5062025/9b661bf2-6db0-11e4-8ff8-2609944111eb.png)

Can you help me please ?

**Comment by themightychris** [comment]
ah, I see. The package name needs to go in app.json, not app.js

**Comment by gtoto007** [comment]
Thank you ! now it's ok !
